name: Windows x64 Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest
    env:
      CARGO_TERM_COLOR: always
      ARTIFACT_NAME: windows-x64-${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build release binary
        run: cargo build --release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: target/release/procmod.exe
          if-no-files-found: error
